# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'SnapKit', '~> 5.6.0'
	pod 'Charts'
	pod 'Kingfisher', '~> 5.0'

  # Pods for AppStore

end
