# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReConvenienceStoreProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'Stubber'
  pod 'Nimble'
  pod 'RxBlocking'
  pod 'RxTest'

  # Pods for ReConvenienceStoreProject

end
