# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PracticeLottie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Then'
pod 'SnapKit', '~> 5.6.0'
pod 'lottie-ios'

  # Pods for PracticeLottie

end
